# Step 1. Import datasets

In [ ]:
import pandas as pd
import numpy as np

applicant_df = pd.read_csv("Simulated applicant dataset - Applicant Dataset.csv")

# Show the first 5 lines
applicant_df.head()

,Age,Entry ID,Gender,City,State Province,Zip Postcode,Application Date,Application Status,Classification Description,Offer Reply Date,...,Room Type offered,Aboriginal/Torres Strait Islander,Course Description,Enrollment Class,1st Room Preference,2nd Room Preference,3rd Room Preference,4th Room Preference,5th Room Preference,6th Room Preference
0,17.0,400001,Male,City 1,Province 1,1234.0,11/1/2024,Offer Accepted,New,11/21/24,...,Single Room,No,Program 1,Undergraduate,Single Room - APT-1,Two Bedroom - APT-3,Five Bedroom - APT-3,Two Bedroom- College-3,Five Bedroom - APT-1,Five Bedroom - APT-5
1,23.0,400002,Female,International,International,NaN,11/16/24,Offer Declined,Returner,11/21/24,...,1-Bedroom,No,Program 2,Postgraduate,Two Bedroom - College-1,Single Room - APT-1,Single Room - APT-5,NaN,NaN,NaN
2,NaN,400003,Prefer not to say,City 3,Province 10,2300.0,11/3/23,Offer Accepted,Returner,11/24/24,...,2-Bedroom,NaN,Program 3,PhD,One Bedroom - College-3,Two Bedroom - College-3,Single Room - APT-1,NaN,NaN,NaN
3,20.0,400004,Other,International,International,NaN,10/5/24,Offer Declined,New,11/30/24,...,5-Bedroom,No,Program 3,Undergraduate,Single Room - APT-1,Single Room - APT-5,One Bedroom - College-3,Two Bedroom- College-5,Five Bedroom - APT-1,NaN
4,22.0,400005,Male,City 5,Province 1,NaN,01/5/23,Offer Accepted,Returner,1/24/24,...,Single Room,No,Program 1,Postgraduate,Two Bedroom - College-5,Two Bedroom - College-5,Single Room - APT-5,NaN,NaN,NaN

In [ ]:
capacity_df = pd.read_csv("Simulated student home rental dataset - Capacity.csv")

# Show the first 5 lines
capacity_df.head()

    Full building name Coded name  Capacity
0   Amazing Apartment       APT-1       200
1  Brilliant Apartment      APT-3       300
2  Fantastic Apartment      APT-5       400
3        Great College  College-1       300
4   Incredible College  College-3       500

In [ ]:
# Import dataset, use skiprows=2 to omit the first 2 rows of text
pricing_df = pd.read_csv("Simulated student home rental dataset - Pricing.csv", skiprows=2)

# Show the first 5 lines
pricing_df.head()

  Room Building    Room Type  Monthly Rent  Monthly Utilities
0         APT-1  Single Room          1000                 50
1         APT-1    1 Bedroom           950                 50
2         APT-1    2 Bedroom           900                 50
3         APT-1    5 Bedroom           800                 50
4         APT-3  Single Room          2000                100

# Step 2. Data transformation

Dataset 1: Applicant

In [ ]:
# Handling missing values
# Check which row has missing values
applicant_df.isnull().sum()

# Replace missing value in Age column with mode
applicant_df['Age'].fillna(applicant_df['Age'].mode()[0], inplace=True)

# Check whether Age column still has missing value
applicant_df.isnull().sum()

/tmp/ipython-input-313187841.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  applicant_df['Age'].fillna(applicant_df['Age'].mode()[0], inplace=True)

Age                                   0
Entry ID                              0
Gender                                0
City                                  0
State Province                        0
Zip Postcode                         12
Application Date                      0
Application Status                    0
Classification Description            0
Offer Reply Date                      2
Offer Sent Date                       2
Apply for Scholarship?                0
Children accompanied?                 0
Partner accompanied?                  0
Location offered                      0
Room Type offered                     0
Aboriginal/Torres Strait Islander     1
Course Description                    0
Enrollment Class                      0
1st Room Preference                   0
2nd Room Preference                   0
3rd Room Preference                   0
4th Room Preference                  15
5th Room Preference                  17
6th Room Preference                  20
dtype: int64

In [ ]:
# See how the data frame looks like (first 5 lines)
applicant_df.head()

,Age,Entry ID,Gender,City,State Province,Zip Postcode,Application Date,Application Status,Classification Description,Offer Reply Date,...,Room Type offered,Aboriginal/Torres Strait Islander,Course Description,Enrollment Class,1st Room Preference,2nd Room Preference,3rd Room Preference,4th Room Preference,5th Room Preference,6th Room Preference
0,17.0,400001,Male,City 1,Province 1,1234.0,11/1/2024,Offer Accepted,New,11/21/24,...,Single Room,No,Program 1,Undergraduate,Single Room - APT-1,Two Bedroom - APT-3,Five Bedroom - APT-3,Two Bedroom- College-3,Five Bedroom - APT-1,Five Bedroom - APT-5
1,23.0,400002,Female,International,International,NaN,11/16/24,Offer Declined,Returner,11/21/24,...,1-Bedroom,No,Program 2,Postgraduate,Two Bedroom - College-1,Single Room - APT-1,Single Room - APT-5,NaN,NaN,NaN
2,20.0,400003,Prefer not to say,City 3,Province 10,2300.0,11/3/23,Offer Accepted,Returner,11/24/24,...,2-Bedroom,NaN,Program 3,PhD,One Bedroom - College-3,Two Bedroom - College-3,Single Room - APT-1,NaN,NaN,NaN
3,20.0,400004,Other,International,International,NaN,10/5/24,Offer Declined,New,11/30/24,...,5-Bedroom,No,Program 3,Undergraduate,Single Room - APT-1,Single Room - APT-5,One Bedroom - College-3,Two Bedroom- College-5,Five Bedroom - APT-1,NaN
4,22.0,400005,Male,City 5,Province 1,NaN,01/5/23,Offer Accepted,Returner,1/24/24,...,Single Room,No,Program 1,Postgraduate,Two Bedroom - College-5,Two Bedroom - College-5,Single Room - APT-5,NaN,NaN,NaN

In [ ]:
# Remove not useful columns: 4th - 6th room preference columns
# Assigned a new data frame name to keep track of different data frame versions
applicant_df1 = applicant_df.drop(columns=['4th Room Preference','5th Room Preference','6th Room Preference'])

# See how the data frame looks like (first 5 lines)
applicant_df1.head()

,Age,Entry ID,Gender,City,State Province,Zip Postcode,Application Date,Application Status,Classification Description,Offer Reply Date,...,Children accompanied?,Partner accompanied?,Location offered,Room Type offered,Aboriginal/Torres Strait Islander,Course Description,Enrollment Class,1st Room Preference,2nd Room Preference,3rd Room Preference
0,17.0,400001,Male,City 1,Province 1,1234.0,11/1/2024,Offer Accepted,New,11/21/24,...,False,False,APT-1,Single Room,No,Program 1,Undergraduate,Single Room - APT-1,Two Bedroom - APT-3,Five Bedroom - APT-3
1,23.0,400002,Female,International,International,NaN,11/16/24,Offer Declined,Returner,11/21/24,...,False,False,APT-3,1-Bedroom,No,Program 2,Postgraduate,Two Bedroom - College-1,Single Room - APT-1,Single Room - APT-5
2,20.0,400003,Prefer not to say,City 3,Province 10,2300.0,11/3/23,Offer Accepted,Returner,11/24/24,...,False,False,APT-5,2-Bedroom,NaN,Program 3,PhD,One Bedroom - College-3,Two Bedroom - College-3,Single Room - APT-1
3,20.0,400004,Other,International,International,NaN,10/5/24,Offer Declined,New,11/30/24,...,False,False,College-1,5-Bedroom,No,Program 3,Undergraduate,Single Room - APT-1,Single Room - APT-5,One Bedroom - College-3
4,22.0,400005,Male,City 5,Province 1,NaN,01/5/23,Offer Accepted,Returner,1/24/24,...,False,False,APT-3,Single Room,No,Program 1,Postgraduate,Two Bedroom - College-5,Two Bedroom - College-5,Single Room - APT-5

In [ ]:
# Adding a new column with different values using logic
applicant_df1["Student Type"] = applicant_df1["State Province"].apply(lambda x: "International" if x == "International" else "Domestic")


# See how the data frame looks like (first 5 lines)
applicant_df1.head()

,Age,Entry ID,Gender,City,State Province,Zip Postcode,Application Date,Application Status,Classification Description,Offer Reply Date,...,Partner accompanied?,Location offered,Room Type offered,Aboriginal/Torres Strait Islander,Course Description,Enrollment Class,1st Room Preference,2nd Room Preference,3rd Room Preference,Student Type
0,17.0,400001,Male,City 1,Province 1,1234.0,11/1/2024,Offer Accepted,New,11/21/24,...,False,APT-1,Single Room,No,Program 1,Undergraduate,Single Room - APT-1,Two Bedroom - APT-3,Five Bedroom - APT-3,Domestic
1,23.0,400002,Female,International,International,NaN,11/16/24,Offer Declined,Returner,11/21/24,...,False,APT-3,1-Bedroom,No,Program 2,Postgraduate,Two Bedroom - College-1,Single Room - APT-1,Single Room - APT-5,International
2,20.0,400003,Prefer not to say,City 3,Province 10,2300.0,11/3/23,Offer Accepted,Returner,11/24/24,...,False,APT-5,2-Bedroom,NaN,Program 3,PhD,One Bedroom - College-3,Two Bedroom - College-3,Single Room - APT-1,Domestic
3,20.0,400004,Other,International,International,NaN,10/5/24,Offer Declined,New,11/30/24,...,False,College-1,5-Bedroom,No,Program 3,Undergraduate,Single Room - APT-1,Single Room - APT-5,One Bedroom - College-3,International
4,22.0,400005,Male,City 5,Province 1,NaN,01/5/23,Offer Accepted,Returner,1/24/24,...,False,APT-3,Single Room,No,Program 1,Postgraduate,Two Bedroom - College-5,Two Bedroom - College-5,Single Room - APT-5,Domestic

In [ ]:
# Replacing buildings' code names with their full names (which are disclosed in the Capacity sheet)
applicant_df1['Location offered'] = applicant_df1['Location offered'].replace({
    'APT-1': 'Amazing Apartment',
    'APT-3': 'Brilliant Apartment',
    'APT-5': 'Fantastic Apartment',
    'College-1': 'Great College',
    'College-3': 'Incredible College',
    'College-5': 'Wonderful College'
})

# See how the data frame looks like (first 5 lines)
applicant_df1.head()

,Age,Entry ID,Gender,City,State Province,Zip Postcode,Application Date,Application Status,Classification Description,Offer Reply Date,...,Partner accompanied?,Location offered,Room Type offered,Aboriginal/Torres Strait Islander,Course Description,Enrollment Class,1st Room Preference,2nd Room Preference,3rd Room Preference,Student Type
0,17.0,400001,Male,City 1,Province 1,1234.0,11/1/2024,Offer Accepted,New,11/21/24,...,False,Amazing Apartment,Single Room,No,Program 1,Undergraduate,Single Room - APT-1,Two Bedroom - APT-3,Five Bedroom - APT-3,Domestic
1,23.0,400002,Female,International,International,NaN,11/16/24,Offer Declined,Returner,11/21/24,...,False,Brilliant Apartment,1-Bedroom,No,Program 2,Postgraduate,Two Bedroom - College-1,Single Room - APT-1,Single Room - APT-5,International
2,20.0,400003,Prefer not to say,City 3,Province 10,2300.0,11/3/23,Offer Accepted,Returner,11/24/24,...,False,Fantastic Apartment,2-Bedroom,NaN,Program 3,PhD,One Bedroom - College-3,Two Bedroom - College-3,Single Room - APT-1,Domestic
3,20.0,400004,Other,International,International,NaN,10/5/24,Offer Declined,New,11/30/24,...,False,Great College,5-Bedroom,No,Program 3,Undergraduate,Single Room - APT-1,Single Room - APT-5,One Bedroom - College-3,International
4,22.0,400005,Male,City 5,Province 1,NaN,01/5/23,Offer Accepted,Returner,1/24/24,...,False,Brilliant Apartment,Single Room,No,Program 1,Postgraduate,Two Bedroom - College-5,Two Bedroom - College-5,Single Room - APT-5,Domestic

In [ ]:
cols = ['1st Room Preference', '2nd Room Preference','3rd Room Preference']

applicant_df1[cols] = applicant_df1[cols].replace({
    'Single Room - APT-1': 'Single Room - Amazing Apartment',
    'Single Room - APT-3': 'Single Room - Brilliant Apartment',
    'Single Room - APT-5': 'Single Room - Fantastic Apartment',
    'Single Room - College-1': 'Single Room - Great College',
    'Single Room - College-3': 'Single Room - Incredible College',
    'Single Room - College-5': 'Single Room - Wonderful College',
    'One Bedroom - APT-1': '1-Bedroom - Amazing Apartment',
    'One Bedroom - APT-3': '1-Bedroom - Brilliant Apartment',
    'One Bedroom - APT-5': '1-Bedroom - Fantastic Apartment',
    'One Bedroom - College-1': '1-Bedroom - Great College',
    'One Bedroom - College-3': '1-Bedroom - Incredible College',
    'One Bedroom - College-5': '1-Bedroom - Wonderful College',
    'Two Bedroom - APT-1': '2-Bedroom - Amazing Apartment',
    'Two Bedroom - APT-3': '2-Bedroom - Brilliant Apartment',
    'Two Bedroom - APT-5': '2-Bedroom - Fantastic Apartment',
    'Two Bedroom - College-1': '2-Bedroom - Great College',
    'Two Bedroom - College-3': '2-Bedroom - Incredible College',
    'Two Bedroom - College-5': '2-Bedroom - Wonderful College',
    'Five Bedroom - APT-1': '5-Bedroom - Amazing Apartment',
    'Five Bedroom - APT-3': '5-Bedroom - Brilliant Apartment',
    'Five Bedroom - APT-5': '5-Bedroom - Fantastic Apartment',
    'Five Bedroom - College-1': '5-Bedroom - Great College',
    'Five Bedroom - College-3': '5-Bedroom - Incredible College',
    'Five Bedroom - College-5': '5-Bedroom - Wonderful College'
})

# See how the data frame looks like
applicant_df1

,Age,Entry ID,Gender,City,State Province,Zip Postcode,Application Date,Application Status,Classification Description,Offer Reply Date,...,Partner accompanied?,Location offered,Room Type offered,Aboriginal/Torres Strait Islander,Course Description,Enrollment Class,1st Room Preference,2nd Room Preference,3rd Room Preference,Student Type
0,17.0,400001,Male,City 1,Province 1,1234.0,11/1/2024,Offer Accepted,New,11/21/24,...,False,Amazing Apartment,Single Room,No,Program 1,Undergraduate,Single Room - Amazing Apartment,2-Bedroom - Brilliant Apartment,5-Bedroom - Brilliant Apartment,Domestic
1,23.0,400002,Female,International,International,NaN,11/16/24,Offer Declined,Returner,11/21/24,...,False,Brilliant Apartment,1-Bedroom,No,Program 2,Postgraduate,2-Bedroom - Great College,Single Room - Amazing Apartment,Single Room - Fantastic Apartment,International
2,20.0,400003,Prefer not to say,City 3,Province 10,2300.0,11/3/23,Offer Accepted,Returner,11/24/24,...,False,Fantastic Apartment,2-Bedroom,NaN,Program 3,PhD,1-Bedroom - Incredible College,2-Bedroom - Incredible College,Single Room - Amazing Apartment,Domestic
3,20.0,400004,Other,International,International,NaN,10/5/24,Offer Declined,New,11/30/24,...,False,Great College,5-Bedroom,No,Program 3,Undergraduate,Single Room - Amazing Apartment,Single Room - Fantastic Apartment,1-Bedroom - Incredible College,International
4,22.0,400005,Male,City 5,Province 1,NaN,01/5/23,Offer Accepted,Returner,1/24/24,...,False,Brilliant Apartment,Single Room,No,Program 1,Postgraduate,2-Bedroom - Wonderful College,2-Bedroom - Wonderful College,Single Room - Fantastic Apartment,Domestic
5,20.0,400006,Female,International,International,1234.0,02/02/23,Offer Declined,New,02/13/24,...,False,Wonderful College,5-Bedroom,No,Program 2,Postgraduate,2-Bedroom - Brilliant Apartment,2-Bedroom - Amazing Apartment,1-Bedroom - Wonderful College,International
6,23.0,400007,Female,International,International,2000.0,03/03/24,Offer Declined,New,03/1/24,...,False,Wonderful College,5-Bedroom,No,Program 3,Postgraduate,Single Room - APT 1,One Bedroom - APT 3,Single Room - Fantastic Apartment,International
7,25.0,400008,Male,City 8,Province 2,NaN,04/04/24,Offer Accepted,New,03/14/24,...,True,Fantastic Apartment,Single Room,No,Program 1,Postgraduate,Single Room - Fantastic Apartment,Single Room - Brilliant Apartment,2-Bedroom - Incredible College,Domestic
8,21.0,400009,Male,City 9,Province 9,NaN,05/05/24,Offer Accepted,New,5/30/24,...,False,Great College,5-Bedroom,No,Program 2,Undergraduate,1-Bedroom - Amazing Apartment,Single Room - Brilliant Apartment,5-Bedroom - Brilliant Apartment,Domestic
9,20.0,400010,Prefer not to say,International,International,1234.0,06/06/23,Offer Accepted,Returner,6/19/24,...,False,Brilliant Apartment,5-Bedroom,No,Program 1,PhD,Single Room - Amazing Apartment,1-Bedroom - Fantastic Apartment,Single Room - Fantastic Apartment,International
10,19.0,400011,Female,International,International,NaN,07/07/23,Offer Accepted,Returner,7/13/24,...,True,Fantastic Apartment,Single Room,No,Program 2,PhD,5-Bedroom - Brilliant Apartment,5-Bedroom - Amazing Apartment,5-Bedroom - Fantastic Apartment,International
11,21.0,400012,Female,City 12,Province 3,2100.0,08/08/24,Offer Accepted,Returner,8/20/24,...,False,Fantastic Apartment,Single Room,No,Program 2,Undergraduate,Single Room - Amazing Apartment,Single Room - Brilliant Apartment,Single Room - Fantastic Apartment,Domestic
12,22.0,400013,Prefer not to say,International,International,NaN,09/09/23,Offer Accepted,Returner,NaN,...,True,Brilliant Apartment,2-Bedroom,No,Program 1,PhD,5-Bedroom - Fantastic Apartment,5-Bedroom - Amazing Apartment,Single Room - Wonderful College,International
13,25.0,400014,Prefer not to say,City 14,Province 3,1234.0,10/10/24,Offer Accepted,Returner,9/21/24,...,False,Fantastic Apartment,1-Bedroom,No,Program 3,Undergraduate,1-Bedroom - Fantastic Apartment,Single Room - Amazing Apartment,Single Room - Fantastic Apartment,Domestic
14,20.0,400015,Male,City 15,International,1234.0,10/20/23,Offer Accepted,New,11/10/23,...,True,Fantastic Apartment,1-Bedroom,No,Program 2,PhD,2-Bedroom - Fantastic Apartment,5-Bedroom - Brilliant Apartment,1-Bedroom - Fantastic Apartment,International
15,20.0,400016,Male,City 16,Province 3,NaN,10/29/23,Offer Declined,New,11/17/23,...,False,Wonderful College,5-Bedroom,Yes,Program 1,Undergraduate,1-Bedroom - Great College,Single Room - Brilliant Apartment,Single Room - Fantastic Apartment,Domestic
16,21.0,400017,Prefer not to say,International,International,NaN,11/25/23,Offer Accepted,New,12/12/23,...,False,Amazing Apartment,1-Bedroom,No,Program 1,Undergraduate,Single Room - Amazing Apartment,1-Bedroom - Amazing Apartment,Single Room - Fantastic Apartment,International
17,18.0,400018,Male,City 18,Province 9,1234.0,11/30/24,Offer Accepted,Returner,12/14/23,...,False,Great College,2-Bedroom,No,Program 1,PhD,2-Bedroom - Amazing Apartment,1-Bedroom - Brilliant Apartment,2-Bedroom - Fantastic Apartment,Domestic
18,21.0,400019,Other,International,International,NaN,11/01/23,Offer Declined,New,11/20/23,...,False,Wonderful College,5-Bedroom,No,Program 1,Undergraduate,Single Room - Amazing Apartment,Single Room - Amazing Apartment,5-Bedroom - Fantastic Apartment,International
19,24.0,400020,Prefer not to say,City 20,Province 9,NaN,12/12/24,Offer Accepted,New,NaN,...,False,Amazing Apartment,1-Bedroom,No,Program 1,Postgraduate,1-Bedroom - Amazing Apartment,2-Bedroom - Amazing Apartment,Single Room - Fantastic Apartment,Domestic
20,22.0,400021,Female,International,International,NaN,10/01/23,Offer Accepted,New,11/14/23,...,False,Amazing Apartment,2-Bedroom,No,Program 2,PhD,Single Room - Amazing Apartment,1-Bedroom - Brilliant Apartment,5-Bedroom - Fantastic Apartment,International

Dataset 2.2 Pricing

Add a column called "Total Monthly Cost", which is the sum of monthly rent and monthly utilities

In [ ]:
pricing_df['Total Monthly Cost'] = (
    pricing_df['Monthly Rent'] + pricing_df['Monthly Utilities']
)

# See how the data frame looks like (first 5 lines)
pricing_df.head()

,Room Building,Room Type,Monthly Rent,Monthly Utilities,Total Monthly Cost
0,APT-1,Single Room,1000,50,1050
1,APT-1,1 Bedroom,950,50,1000
2,APT-1,2 Bedroom,900,50,950
3,APT-1,5 Bedroom,800,50,850
4,APT-3,Single Room,2000,100,2100

#Step 3. Export the .csv files that have undergone the data-cleaning process using Python, because they will be used in Power BI next to create the dashboard

In [ ]:
from google.colab import files

applicant_df1.to_csv('applicant.csv', index=False)
pricing_df.to_csv('pricing.csv', index=False)

# Download the file
files.download('applicant.csv')
files.download('pricing.csv')